// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int n = Integer.parseInt(args[0]);
	   double count = 0;
	   double count1 = 0; 
	  for(int i = 0; i < n; i++) {
		double random = Math.random();
		if (random < 0.5 ){
		count ++ ; 
		} else {
			count1++;
		}
	  }
	  double ratio = (count1 / count);
	  if(count != 0){
		System.out.println("> 0.5: " + count1 + " times");
		System.out.println("<= 0.5: " + count + " times");
		System.out.println("Ratio: " + ratio);
	  }


	}
}
